### PR TITLE
Make a link in README not to need to copy and paste

### PR DESCRIPTION
**Pull request by cohei**

### CODE REVIEW

**Comment by cohei** [comment]
Github flavoured markdown doesn't support Javascript links. (for bookmarklets) https://github.com/github/markup/issues/79

;(

**Comment by cohei** [comment]
https://github.com/github/markup/issues/79 Github flavoured markdown doesn't support Javascript links. (for bookmarklets) 

;(

**Comment by Artistan** [comment]
works in github pages like https://retrography.github.io/VUTt/,
  but not in gists (same VUTt Link) https://gist.github.com/Artistan/2f212b8ea3d1ec0fbe3e1be1fbb7a987

**Comment by cohei** [comment]
I decided to use GitHub Pages.
Thanks for your advice!

**Pull request closed without merging**
